### ISSUE TITLE
The server crashes if IfcConvert executable is not found.

### ISSUE THREAD

**Issue by fklingler** [mitmadness/chuck#2]
```
verbose: convqueue: job #3 [processor/exec-ifcopenshell/convert-start] Converting "C:\Users\Francois\AppData\Local\Temp\chuck-dl-assets-1497965078228\1497964291696-Factory.ifc" from IFC to Collada
Error: spawn IfcConvert ENOENT
    at exports._errnoException (util.js:1033:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[nodemon] app crashed - waiting for file changes before starting...
```

Not sure if this should be here or in [chuck-ifc](https://github.com/mitmadness/chuck-ifc). The server should not crash completely but instead intercept the error and mark the job as failed.

This current behavior is even more wrong since when this happens, every time the server restarts, the job retries, and the same error happens so the server crashes. I have to remove the job in redis or wait for the job "timeout" to continue my tests.

**Comment by toverux** [comment]
Hi @fklingler, thanks for the feedback!

The problem effectively comes from chuck-ifc as chuck does not know anything about IFC.
You're right, a better error message when the executable is not found would be cool, as well as making that path configurable via an environment variable.

I will also look at the reason that makes the process crash, chuck is usually more resilient than that!

**Comment by toverux** [comment]
Solved by https://github.com/mitmadness/chuck-ifc/commit/81333c2d7331b839dec8ba5999eb298c4942100b. When there is no listener attached for `error` events, Node has a special behaviour, it throws an exception (so the error is not swallowed by The Void). The exception is not caught (async async) and the server crashes. It's now handled properly.

Also, the path of IfcConvert is now configurable with https://github.com/mitmadness/chuck-ifc/commit/ef3071c4207b09164e442cde121fce301e27dde9.

And finally : chuck now catches the uncaught exceptions just like it does with unhandled rejections (logging + `process.exit(1)`) : https://github.com/mitmadness/chuck/commit/8454af441d04293f4f84fdd2805928145b25db18.
